### PR TITLE
Update nose.yml

### PR DESCRIPTION
**Pull request by mukundvarma**
Make automated tests run on windows, mac and linux

### CODE REVIEW

**Comment by mukundvarma** [comment]
Do you want to add a test that would fail, re:  #30

**Comment by velicanu** [comment]
most of the tests using `tempfile` are failing for me on windows right now, including the pipeline / integration_test. is this picking up those errors?

**Comment by velicanu** [comment]
lol github, good effort. i just realized it's saying all tests pass on windows


expense-fail

**Comment by mukundvarma** [comment]
Seem to be passing on github!
`https://github.com/velicanu/expenses/pull/31/checks?check_run_id=863510681#step:5:23`

**Pull request merged**
